### ISSUE TITLE
Vector_FindIndex, returns 0 even if the index is invalid.

### ISSUE THREAD

**Issue by ners-xd** [skuzzis/pawn-vectors#6]
The Vector_FindIndex function returns 0 even if it is invalid, make it so it returns -1 in that case.

**Comment by skuzzis** [comment]
Can you please put a screenshot here? From ingame or something?

**Comment by ners-xd** [comment]
My phone number is 1000, however I can message any other random number and it will be sent to me because I am playerid 0.
![image](https://user-images.githubusercontent.com/85985080/122192437-5454dd80-ce9c-11eb-971e-cb7836466820.png)

**Comment by skuzzis** [comment]
Solved in pull request #8.
